apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: exp
  labels:
    app: backend
spec:
  ports:
    - name: grpc-web # istio refers this value as protocol
      port: 9000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hjcian/emoji:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
